Assigment pandas EloiAncellin
x-datascience-datacamp/datacamp-assignment-pandas pull request #10
Opened 2020-11-09 20:10 UTC by EloiAncellin

2020-11-09 20:14 UTC, agramfort commented
good job @EloiAncellin 

can you just remove all the unecessary files ? you should not need to add any new file in this PR

2020-11-09 20:17 UTC, EloiAncellin commented
Bonjour Monsieur,

C’est fait !

Excellent soirée,

Eloi 

> Le 9 nov. 2020 à 21:14, Alexandre Gramfort <notifications@github.com> a écrit :
> 
> 
> good job @EloiAncellin <https://github.com/EloiAncellin>
> can you just remove all the unecessary files ? you should not need to add any new file in this PR
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/x-datascience-datacamp/datacamp-assignment-pandas/pull/10#issuecomment-724252730>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ALYWMQAHDRMVL4O33E2XGK3SPBETBANCNFSM4TPZRRGA>.
>

2020-11-09 20:22 UTC, agramfort commented on .idea/.gitignore
> +/workspace.xml
please remove all  the .idea folder

2020-11-09 20:22 UTC, agramfort commented on .idea/.gitignore
> +/workspace.xml
I see 10 files modified. I should see only one

2020-11-09 20:22 UTC, EloiAncellin commented on .idea/.gitignore
> +/workspace.xml
I have made an mistake and deleted the test file, thus, I am correcting my errors...

2020-11-09 20:32 UTC, agramfort commented
you should not change the data/referendum.csv file

2020-11-09 20:34 UTC, EloiAncellin commented
Did I do it ?

> Le 9 nov. 2020 à 21:32, Alexandre Gramfort <notifications@github.com> a écrit :
> 
> 
> you should not change the data/referendum.csv file
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/x-datascience-datacamp/datacamp-assignment-pandas/pull/10#issuecomment-724261650>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ALYWMQA6ZAM3SD667Y5N3M3SPBGWTANCNFSM4TPZRRGA>.
>

2020-11-09 20:35 UTC, agramfort commented
see the diff in your PR

https://github.com/x-datascience-datacamp/datacamp-assignment-pandas/pull/10/files

I see 3 files changed

2020-11-10 08:57 UTC, tomMoral commented
If you are finished, you can sign up for this RAMP challenge: https://ramp.studio/events/brevet_datacamp2020
This is what we are going to do this afternoon. The goal is to try and solve the challenge.
You need to click on the blue button: `Join the event` and I need to approve your participation so send me a message once you have done this.
You can then read the starting kit and go to the left menu to submit your solutions in the sandbox.

2020-11-10 09:14 UTC, tomMoral requested changes
Nice one!

Just fix pep8.

2020-11-10 09:14 UTC, tomMoral commented on pandas_questions.py
> +             {'region_code': 'code_reg', 'name_x': 'name_reg', 'code_y': 'code_dep', 'name_y': 'name_dep'}
Not pep8.

2020-11-10 09:14 UTC, tomMoral commented on pandas_questions.py
> +            geo_referundum['Registered'] - geo_referundum['Abstentions'] - geo_referundum['Null'])
pep8

2022-01-06 18:49 UTC, closed without merging