Pandas assignment - Lotfi Kobrosly
x-datascience-datacamp/datacamp-assignment-pandas pull request #13
Opened 2020-11-10 00:17 UTC by LotfiKobrosly

2020-11-10 09:03 UTC, tomMoral commented
If you are finished, you can sign up for this RAMP challenge: https://ramp.studio/events/brevet_datacamp2020
This is what we are going to do this afternoon. The goal is to try and solve the challenge.
You need to click on the blue button: `Join the event` and I need to approve your participation so send me a message once you have done this.
You can then read the starting kit and go to the left menu to submit your solutions in the sandbox.

2020-11-10 09:12 UTC, tomMoral requested changes
Can you update your PR to remove extra files and use `merge` to merge the dataframe?

2020-11-10 09:12 UTC, tomMoral commented on data/.~lock.departments.csv#
> +,lotfi,lotfi-Lenovo-ideapad-330-15IKB,10.11.2020 00:20,file:///home/lotfi/.config/libreoffice/4;
You need to be carefull and not commit extra files.

Can you remove them?

2020-11-10 09:12 UTC, tomMoral commented on pandas_questions.py
> +    #             Choice A, Choice B
Clean up your debugging comments.

2020-11-10 09:12 UTC, tomMoral commented on pandas_questions.py
> +
Nice one (the other did not do this)! It is not mandatory but you can remove `Raises` when you don't raise error.

2020-11-10 09:12 UTC, tomMoral commented on pandas_questions.py
> +        df.loc[mask, "name_reg"] = row["name"]
Could you try to do this with the `merge` method?
This for loop is quite inefficient I think

2020-11-10 09:12 UTC, tomMoral commented on pandas_questions.py
> +        df["name_reg"] = df["name_reg"].mask(mask, row["name_reg"]).to_numpy()
Same, use `pd.merge`

2020-11-10 12:37 UTC, LotfiKobrosly commented on data/.~lock.departments.csv#
> +,lotfi,lotfi-Lenovo-ideapad-330-15IKB,10.11.2020 00:20,file:///home/lotfi/.config/libreoffice/4;
I cannot see these files in the directory (even with `ls -lart` ). Could you suggest me how I can fix it please?

2020-11-10 12:40 UTC, LotfiKobrosly commented on data/.~lock.departments.csv#
> +,lotfi,lotfi-Lenovo-ideapad-330-15IKB,10.11.2020 00:20,file:///home/lotfi/.config/libreoffice/4;
I guess it is due to me opening the `.csv` files using LibreOffice

2020-11-10 13:08 UTC, agramfort commented on data/.~lock.departments.csv#
> +,lotfi,lotfi-Lenovo-ideapad-330-15IKB,10.11.2020 00:20,file:///home/lotfi/.config/libreoffice/4;
`git rm .~lock.departments.csv#` would remove one file

2020-11-10 13:30 UTC, LotfiKobrosly commented
Changes added thank you !

2020-11-10 23:31 UTC, tomMoral requested changes
Still a few comments on the PR.

2020-11-10 23:31 UTC, tomMoral commented on pandas_questions.py
> +        df["geometry"].append(region_map.loc[mask]["geometry"].values[0])
You can also use a merge here.

2020-11-11 11:01 UTC, tomMoral requested changes
Look mostly good, except for the extra `pd.DataFrame` in `load_data`.

2020-11-11 13:25 UTC, LotfiKobrosly commented on pandas_questions.py
> +        suffixes=['_dep', '_reg'])
I actually usually do that :)

2020-11-11 20:53 UTC, LotfiKobrosly commented
All done thank you for your remarks!

2020-11-12 08:04 UTC, tomMoral approved these changes
LGTM!!

2020-11-12 08:04 UTC, closed without merging